CREATE TABLE IF NOT EXISTS BENEFICIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  VALOR DECIMAL(15,2) NOT NULL CHECK (VALOR >= 0),
  ATIVO BOOLEAN DEFAULT TRUE,
  VERSION BIGINT DEFAULT 0 NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_BENEFICIO_ATIVO ON BENEFICIO(ATIVO);
CREATE INDEX IF NOT EXISTS IDX_BENEFICIO_NOME ON BENEFICIO(NOME);
